version: 2

project_name: bdinfo

before:
  hooks:
    - go mod tidy

builds:
  - id: bdinfo
    main: ./cmd/bdinfo
    binary: bdinfo
    env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
    ldflags:
      - -s -w
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64

archives:
  - id: default
    ids:
      - bdinfo
    formats:
      - tar.gz
    format_overrides:
      - goos: windows
        formats:
          - zip
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: "checksums.txt"

changelog:
  use: github
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
      - "^ci:"
      - "^build:"
      - "^refactor:"

homebrew_casks:
  - name: bdinfo
    binaries:
      - bdinfo
    homepage: "https://github.com/s0up4200/go-bdinfo"
    description: "Go rewrite of BDInfo."
    repository:
      owner: s0up4200
      name: "{{ .ProjectName }}"
