version: 2

project_name: bdinfo

before:
  hooks:
    - go mod tidy

builds:
  - id: bdinfo
    main: ./cmd/bdinfo
    binary: bdinfo
    env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
    ldflags:
      - -s -w -X main.version={{ .Version }}
    goos:
      - linux
      - darwin
      - windows
      - freebsd
    goarch:
      - amd64
      - arm
      - arm64
    goarm:
      - 6
    ignore:
      - goos: windows
        goarch: arm
      - goos: windows
        goarch: arm64
      - goos: darwin
        goarch: arm
      - goos: freebsd
        goarch: arm
      - goos: freebsd
        goarch: arm64

archives:
  - id: default
    ids:
      - bdinfo
    formats:
      - tar.gz
    format_overrides:
      - goos: windows
        formats:
          - zip
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - Merge pull request
      - Merge remote-tracking branch
      - Merge branch
      - go mod tidy
      - "^Brew cask update"
      - "goreleaserbot"
  groups:
    - title: "New Features"
      regexp: "^.*feat[(\\w)]*:+.*$"
      order: 0
    - title: "Bug Fixes"
      regexp: "^.*fix[(\\w)]*:+.*$"
      order: 10
    - title: "Other Changes"
      regexp: "^.*(chore|docs|style|refactor|test|perf|security|build|ci)[(\\w)]*:+.*$"
      order: 20

homebrew_casks:
  - name: bdinfo
    binaries:
      - bdinfo
    homepage: "https://github.com/s0up4200/go-bdinfo"
    description: "Go rewrite of BDInfo."
    repository:
      owner: s0up4200
      name: "go-bdinfo"
