# This file was generated by GoReleaser. DO NOT EDIT.
cask "bdinfo" do
  name "bdinfo"
  desc "Go rewrite of BDInfo."
  homepage "https://github.com/autobrr/go-bdinfo"
  version "0.2.2"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "bdinfo"

  on_macos do
    on_intel do
      url "https://github.com/autobrr/go-bdinfo/releases/download/v#{version}/bdinfo_#{version}_darwin_amd64.tar.gz"
      sha256 "15c1d92ccac912a48af1a4263a4b3ad2a879ebae420c6cce92ba4223613d1938"
    end
    on_arm do
      url "https://github.com/autobrr/go-bdinfo/releases/download/v#{version}/bdinfo_#{version}_darwin_arm64.tar.gz"
      sha256 "db91097b3176375b390fdf682263e50b005289a481e430981fa4d3a6f24bc8fc"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/autobrr/go-bdinfo/releases/download/v#{version}/bdinfo_#{version}_linux_amd64.tar.gz"
      sha256 "684d5986968fc5cfa07757a39597fcca639667f825517423266bc978c077faa9"
    end
    on_arm do
      url "https://github.com/autobrr/go-bdinfo/releases/download/v#{version}/bdinfo_#{version}_linux_arm64.tar.gz"
      sha256 "07eac6bfb5a28e212e6a01362fefcf8095763eab2d53ee9090cca0227eff152c"
    end
  end

  # No zap stanza required
end
